version: '3.8'

services:
  wayak-server:
    build: .cloud/docker
    image: wayak-server
    # depends_on:
      # - mysql
      # - redis
      # - mysql-test
    volumes:
      - ./:/application:cached
      # - /Volumes/WAYAK/wayak/public:/application/public
  mysql-db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wayak
    volumes:
      - db-data:/var/lib/mysql:cached
  nginx:
    image: nginx:alpine
    ports:
      - "8001:8001"
    volumes:
      - .cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - wayak-server
  redis_dev:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: --port 6379
    expose:
        - "6379"
    volumes:
      - .cloud/redis/data/dev:/data
  bard:
    build:
      context: .cloud/docker/bard/
      dockerfile: Dockerfile
    environment:
      _BARD_API_KEY: "cghW7kByc5YYcD7dOnznChWJMugE4pul0c1-9c8MW3pPX6aTFYE2TkHbtIxD7RCYg2WnMg."
    volumes:
      - .cloud/bard/app:/app/code/
      - /Users/daniel/Documents/GitHub/wayak/public/design/template:/app/images/
    ports:
      - "5000:5000"
  # redis_uat:
  #   image: redis:alpine
  #   ports:
  #     - "6380:6380"
  #   command: --port 6380
  #   expose:
  #       - "6380"
  #   volumes:
  #     - .cloud/redis/data/uat:/data
  # redis_pro:
  #   image: redis:alpine
  #   ports:
  #     - "6381:6381"
  #   command: --port 6381
  #   expose:
  #       - "6381"
  #   volumes:
  #     - .cloud/redis/data/pro:/data
  # mongo:
  #   image: mongo
  #   volumes:
  #     - .cloud/mongodb/data:/data/db
  #   ports:
  #     - "27017:27017"
  # nodejs:
  #   build:
  #     context: ./.cloud/nodejs
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - SERVER_PORT=8080
  #   volumes:
  #     - ./.cloud/nodejs:/usr/src/app
  #   # command: npm run debug
  # elastic:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
  #   # container_name: es01
  #   environment:
  #     - discovery.type=single-node
  #     # - node.name=es01
  #     # - cluster.name=es-docker-cluster
  #     # - discovery.seed_hosts=es02,es03
  #     # - cluster.initial_master_nodes=es01,es02,es03
  #     # - bootstrap.memory_lock=true
  #     # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   # ulimits:
  #   #   memlock:
  #   #     soft: -1
  #   #     hard: -1
  #   volumes:
  #     - ./.cloud/elastic:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   # networks:
  #   #   - elastic
  #   depends_on:
  #     - kibana
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.9.3
  #   # volumes:
  #   #   - ./.cloud/elastic/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
  #   ports:
  #       - 5601:5601
  #   environment:
  #       ELASTICSEARCH_URL: http://elastic:9200
  #       ELASTICSEARCH_HOSTS: http://elastic:9200
volumes:
  db-data:
  public-design-template:
